### ISSUE TITLE
payee worker outputArchiveStore 优化

### ISSUE THREAD

**Issue by cw35** [fox-one/compound#12]
outputArchiveStore 是多余的吧，checkpoint 不就是干这个的么

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/payee.go#L129

**Comment by cw35** [comment]
把所有代码都直接放到 mysql tx 里不是推荐的做法吧。。。
而且，在 proposal 的那些 handler 中还出现了 tx 嵌套。mysql 不支持 tx 嵌套的。。

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/payee.go#L132-L147

**Comment by firefly1126** [comment]
FIXED  https://github.com/fox-one/compound/commit/43302f39438a445aaeb73a2bc4b2be2a82cff1b7
