### ISSUE TITLE
[bug] 用户提现等操作，必须检查 output.sender

### ISSUE THREAD

**Issue by cw35** [fox-one/compound#13]
对于一些可能会影响到用户 valult 安全的操作，必须要检查 sender，确认是本人转账

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/payee.go#L193

**Comment by firefly1126** [comment]
FIXED https://github.com/fox-one/compound/commit/11b177c4610251bac7f198b26fe206af4fb55f91
