### ISSUE TITLE
snapshot worker: price 优化

### ISSUE THREAD

**Issue by cw35** [fox-one/compound#14]
db tx 中不要做太多无用的操作，尽量让 tx 尽快结束。此处 find market 等等的操作都不需要在 tx 中操作。

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/price.go#L19-L154

**Comment by cw35** [comment]
price tickers 不足的时候不保存？那是不是永远都最多只有2个？m/n 多签，m > 2 的话价格就永远没法达成一致了吧？

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/price.go#L90-L92

**Comment by cw35** [comment]
最坏的情况，每个相邻的价格都偏差 4.99个点？那假如5个价格的话，1, 1.049, 1.100401, 1.154320649, 1.2108823608。这样处理不行吧？
是不是应该直接用中位数，或者用均值来过滤，而不是用相邻的两个价格来过滤

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/price.go#L102-L111

**Comment by firefly1126** [comment]
FIXED https://github.com/fox-one/compound/commit/9ebdbe929132eb086317cf8b4010dcc7452b979f
