### ISSUE TITLE
snapshot worker: withdraw 做必要检查以及更新 market

### ISSUE THREAD

**Issue by cw35** [fox-one/compound#15]
提现 reserves 时，检查下 reserves 是否充足？另外在更新一下 makret 的 TotalCash 和 Reserves?

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/withdraw.go#L13

**Comment by firefly1126** [comment]
FIXED https://github.com/fox-one/compound/commit/d4b4d8e49002d3a5eb1b904b1dc6de4f158ced13
