### ISSUE TITLE
snapshot worker: allow list

### ISSUE THREAD

**Issue by cw35** [fox-one/compound#16]
这里是 RemoveAllowListScope ?

https://github.com/fox-one/compound/blob/9e3128cfdfdddeda06534d6e4a6c8afa0318919e/worker/snapshot/allow_list.go#L23

**Comment by cw35** [comment]
没太理解 AllowListScopes 的用途。不在白名单里的 scope 就是无效的？这个的意义是？

如果需要限制 scope 的话，那在 AddAllowList, RemoveAllowListScope 是不是也需要对相应的 AllowList 进行清理？

**Comment by firefly1126** [comment]
AllowListScopes的作用是用来控制白名单生效的业务范围，这样可以灵活控制白名单的运用范围。比如只在清算这个业务范围内运用白名单限制，其他业务不影响。这样易于扩展。

**Comment by firefly1126** [comment]
`那在 AddAllowList, RemoveAllowListScope 是不是也需要对相应的 AllowList 进行清理？`，不需要对allow_list清理。
